symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository

    # Le lien reste valide pendant 1 heure
    lifetime: 3600

    # Empêche de spammer les demandes.
    # Ici une nouvelle demande est possible après 5 minutes.
    throttle_limit: 300

    enable_garbage_collection: true
