<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260901110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute le module des cas cliniques de radiologie et ses référentiels.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE imaging_modality (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, code VARCHAR(50) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A831601A989D9B62 ON imaging_modality (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A831601A77153098 ON imaging_modality (code)');

        $this->addSql('CREATE TABLE case_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_913163BC989D9B62 ON case_category (slug)');

        $this->addSql('CREATE TABLE radiology_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, modality_id INT NOT NULL, category_id INT NOT NULL, author_id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, difficulty VARCHAR(24) NOT NULL, patient_gender VARCHAR(24) NOT NULL, patient_age INT DEFAULT NULL, clinical_context TEXT NOT NULL, training_instruction TEXT DEFAULT NULL, training_placeholder TEXT DEFAULT NULL, expert_description TEXT DEFAULT NULL, diagnosis TEXT DEFAULT NULL, global_discussion TEXT DEFAULT NULL, status VARCHAR(28) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B515D04989D9B62 ON radiology_case (slug)');
        $this->addSql('CREATE INDEX idx_radiology_case_status ON radiology_case (status)');
        $this->addSql('CREATE INDEX idx_radiology_case_published_at ON radiology_case (published_at)');
        $this->addSql('CREATE INDEX IDX_1B515D042D6D889B ON radiology_case (modality_id)');
        $this->addSql('CREATE INDEX IDX_1B515D0412469DE2 ON radiology_case (category_id)');
        $this->addSql('CREATE INDEX IDX_1B515D04F675F31B ON radiology_case (author_id)');

        $this->addSql('CREATE TABLE case_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, radiology_case_id INT NOT NULL, path VARCHAR(2048) NOT NULL, media_type VARCHAR(80) DEFAULT \'IMAGE\' NOT NULL, title VARCHAR(255) DEFAULT NULL, caption TEXT DEFAULT NULL, alt_text VARCHAR(500) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38C55BE072312F8C ON case_media (radiology_case_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_case_primary_media ON case_media (radiology_case_id) WHERE is_primary = true');

        $this->addSql('CREATE TABLE case_reference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, radiology_case_id INT NOT NULL, title VARCHAR(500) NOT NULL, authors VARCHAR(500) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, url VARCHAR(2048) DEFAULT NULL, doi VARCHAR(255) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_808039E872312F8C ON case_reference (radiology_case_id)');

        $this->addSql('ALTER TABLE radiology_case ADD CONSTRAINT FK_RADIOLOGY_CASE_MODALITY FOREIGN KEY (modality_id) REFERENCES imaging_modality (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE radiology_case ADD CONSTRAINT FK_RADIOLOGY_CASE_CATEGORY FOREIGN KEY (category_id) REFERENCES case_category (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE radiology_case ADD CONSTRAINT FK_RADIOLOGY_CASE_AUTHOR FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE case_media ADD CONSTRAINT FK_CASE_MEDIA_CASE FOREIGN KEY (radiology_case_id) REFERENCES radiology_case (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE case_reference ADD CONSTRAINT FK_CASE_REFERENCE_CASE FOREIGN KEY (radiology_case_id) REFERENCES radiology_case (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("INSERT INTO imaging_modality (name, slug, code, active, position, created_at, updated_at) VALUES ('Radiographie', 'radiographie', 'RADIOGRAPHY', true, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('IRM', 'irm', 'MRI', true, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('TDM', 'tdm', 'CT', true, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('Échographie', 'echographie', 'ULTRASOUND', true, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO case_category (name, slug, active, position, created_at, updated_at) VALUES ('Imagerie thoracique', 'imagerie-thoracique', true, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('Neuroradiologie', 'neuroradiologie', true, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('Imagerie abdominale et digestive', 'imagerie-abdominale-et-digestive', true, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE case_reference DROP CONSTRAINT FK_CASE_REFERENCE_CASE');
        $this->addSql('ALTER TABLE case_media DROP CONSTRAINT FK_CASE_MEDIA_CASE');
        $this->addSql('ALTER TABLE radiology_case DROP CONSTRAINT FK_RADIOLOGY_CASE_MODALITY');
        $this->addSql('ALTER TABLE radiology_case DROP CONSTRAINT FK_RADIOLOGY_CASE_CATEGORY');
        $this->addSql('ALTER TABLE radiology_case DROP CONSTRAINT FK_RADIOLOGY_CASE_AUTHOR');
        $this->addSql('DROP TABLE case_reference');
        $this->addSql('DROP TABLE case_media');
        $this->addSql('DROP TABLE radiology_case');
        $this->addSql('DROP TABLE case_category');
        $this->addSql('DROP TABLE imaging_modality');
    }
}
